---
- name: yarn key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Heroku key
  apt_key:
    url: https://cli-assets.heroku.com/apt/release.key 
    state: present

- name: Yarn repo
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"

- name: Heroku repo
  apt_repository:
    repo: "deb https://cli-assets.heroku.com/branches/stable/apt ./"

- name: Install developer packages
  apt:
    name: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - postgresql
    - postgresql-contrib-9.5
    - libmysqlclient-dev
    - yarn
    - redis-tools
    - pgadmin3
    - heroku
    - nodejs
    - coffeescript
    - npm
    - vinagre
    - git-flow
    - libxml2-dev 
    - libxslt1-dev
    - python-dev
    - curl
    - libpq-dev
    - imagemagick
    - libmagickwand-dev


#-- webkit? qtdeclarative5-dev libqt5webkit5-dev
#libqt4-dev libqtwebkit-dev

