---
- name: Disable global Resilio
  tags:
    - service
  service:
    enabled: no
    name: resilio-sync

- name: "Create systemd user service for {{home}}"
  tags:
    - service
  file:
    dest: "{{home}}/.config/systemd/user"
    mode: 0755
    state: directory
    owner: "{{username}}"
    group: "{{username}}"

- name: "Create {{home}}/.sync directory"
  tags:
    - service
  file:
    dest: "{{home}}/.sync"
    state: directory
    mode: 0755
    owner: "{{username}}"
    group: "{{username}}"

- name: Remove my resilio user service as there is one bundled in package
  file:
    dest: "{{home}}/.config/systemd/user/resilio-sync.service"
    state: absent

# - name: Install Resilio user service
#   tags:
#     - service
#   template:
#     src: "../template/resilio-sync.service.j2"
#     dest: "{{home}}/.config/systemd/user/resilio-sync.service"
#     mode: 0644
#     owner: "{{username}}"
#     group: "{{username}}"

- name: Make Resilio config direcotry
  file:
    dest: "{{home}}/.config/resilio-sync"
    state: directory
    mode: 0755
    owner: "{{username}}"
    group: "{{username}}"

- name: Install Resilio config
  template:
    src: ../template/sync.json.j2
    dest: "{{home}}/.config/resilio-sync/config.json"
    mode: 0600
    owner: "{{username}}"
    group: "{{username}}"

- name: "Remove wrong user service in multi-user.target"
  tags:
    - resilio
  file:
    dest: "{{home}}/.config/systemd/user/multi-user.target.wants/resilio-sync.service"
    state: absent

- name: "Disable global resilio service"
  tags:
    - resilio
  shell: "systemctl disable resilio-sync.service"

- name: "Stop global resilio service"
  tags:
    - resilio
  shell: "systemctl stop resilio-sync.service"

# - name: "Fix Resilio service to use default.target not multi-user.target"
#   tags:
#     - resilio
#   lineinfile:
#     dest: "/usr/lib/systemd/user/resilio-sync.service"
#     regexp: "^WantedBy="
#     line: "WantedBy=default.target"

- name: "Enable per user Resilio (for user {{username}})"
  tags:
    - resilio
  shell: "sudo machinectl shell --uid=$(id -u {{username}}) .host  /bin/systemctl -- --user enable resilio-sync.service"
  notify: restart resilio

