---
- hosts: localhost
  become: yes
  become_user: root
  connection: local
  roles:
    - base 
    - resilio
    - keepass2
    - { role: developer, when: "ansible_hostname in ['guattari', 'thinktank']" }
