---
- hosts: localhost
  become: yes
  become_user: root
  connection: local
  roles:
    - base 
    - { role: resilio, when: "ansible_hostname not in ['lovelace', 'bakunin', 'parks']"}
    - keepass2
    - { role: developer, when: "ansible_hostname in ['guattari', 'thinktank', 'ferrerguardia', 'lovelace', 'bakunin', 'parks']" }
