---
- name: Install all necessary packages and update the system
  apt: name={{item}} state=installed update_cache=true
  with_items:
    - cinnamon-desktop-environment
    - nemo
    - chromium-browser
    - thunderbird
    - ubuntu-restricted-addons # flash, mpeg, etc.
    - audacity
    - gimp
    - ttf-mscorefonts-installer
    - emacs24
    - git 
    - imagemagick
    - fortune-mod
    - htop
    - dconf-editor
    - gnome-tweak-tool
    - sysstat

- copy:
    src: "../files/{{item}}"
    dest: "/tmp/{{item}}"
  with_items:
    - slack-desktop-2.5.1-amd64.deb
    - skypeforlinux-64.deb

- name: Install Skype from bundled deb file
  apt:
    deb: "/tmp/{{item}}"
    state: present
  with_items:
    - slack-desktop-2.5.1-amd64.deb
    - skypeforlinux-64.deb



