---
# this arc-theme repo displays a verification failed error
# so we download deb file and install from file.
#    - "deb https://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/ /"
    
# - name: Add Arc theme key
#   apt_key:
#     url: http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_16.04/Release.key
#     state: present

- name: Add Skype key
  apt_key:
    url: https://repo.skype.com/data/SKYPE-GPG-KEY
    state: present

- name: AirVPN key
  apt_key:
    url: https://eddie.website/repository/keys/eddie_maintainer_gpg.key
    state: present

- name: Add repo
  apt_repository: 
    repo: "{{item}}"
    state: present
  with_items:
    - "deb http://eddie.website/repository/apt stable main"
    - ppa:nextcloud-devs/client

- name: Remove arc theme repo
  apt_repository:
    repo: ppa:moka/daily
    state: absent

- name: Accept the EULA for MS core fonts
  shell: "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"
  
- name: Install all necessary packages and update the system
  apt: name={{item}} state=installed update_cache=true
  with_items:
    - systemd-container
    - gnome-shell
    - chrome-gnome-shell
    - nemo
    - chromium-browser
    - thunderbird
    - ubuntu-restricted-addons # flash, mpeg, etc.
    - audacity
    - gimp
    - ttf-mscorefonts-installer
    - vim
    - git 
    - imagemagick 
    - fortune-mod
    - htop
    - dconf-editor
    - gnome-tweak-tool
    - sysstat
    - texlive-xetex
    - texlive-latex-extra
    - texlive-lang-polish
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - gscan2pdf
    - network-manager-openvpn-gnome
    - airvpn
    - nextcloud-client
    - moka-icon-theme
    - faba-icon-theme

- name: Install Keepass CX
  tags:
    - keepassxc
  shell: snap install keepassxc

- name: Run AirVPN on startup
  copy:
    src: ../files/AirVPN.desktop
    dest: "{{home}}/.config/autostart/AirVPN.desktop"
    mode: 0755

- name: Make spool directory need by Brother Driver
  file:
    dest: /var/spool/lpd
    state: directory
    owner: root
    group: root
    mode: 0755

- copy:
    src: "../files/{{item}}"
    dest: "/tmp/{{item}}"
  with_items: "{{bundled_packages}}"

- name: Install packages from bundled deb files
  apt:
    deb: "/tmp/{{item}}"
    state: present
    #force: yes
  with_items: "{{bundled_packages}}"
  ignore_errors: true

- name: Run the hacked Brother installer script
  shell: bash roles/base/files/linux-brprinter-installer-hackd-2.1.1-2

