---
- name: Install NewRelic license key
  copy:
    src: "{{home}}/Akcja Demokracja/Narzędzia/newrelic-infra.yml"
    dest: "/etc/newrelic-infra.yml"
    mode: 0600
    owner: root
    group: root
  notify: restart NewRelic
  ignore_errors: true

- name: Set user tag to current username 
  replace:
    path: "/etc/newrelic-infra.yml"
    regexp: "user: .*"
    replace: "user: {{username}}"
  notify: restart NewRelic
  ignore_errors: true

# echo "license_key: YOUR_LICENSE_KEY" | sudo tee -a /etc/newrelic-infra.yml
